/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class media_jni_NativeMethod */

#ifndef _Included_media_jni_NativeMethod
#define _Included_media_jni_NativeMethod
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     media_jni_NativeMethod
 * Method:    nv21ToI420
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_media_jni_NativeMethod_nv21ToI420
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint,jbyteArray,jbyteArray,jbyteArray);

/*
 * Class:     media_jni_NativeMethod
 * Method:    nv21ToNv12
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_media_jni_NativeMethod_nv21ToNv12
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint,jbyteArray,jbyteArray,jbyteArray);

/*
 * Class:     media_jni_NativeMethod
 * Method:    nv21CutterToI420
 * Signature: ([B[BIIII)V
 */
JNIEXPORT void JNICALL Java_media_jni_NativeMethod_nv21CutterToI420
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint,jbyteArray,jbyteArray,jbyteArray);

/*
 * Class:     media_jni_NativeMethod
 * Method:    nv21CutterToNv12
 * Signature: ([B[BIIII)V
 */
JNIEXPORT void JNICALL Java_media_jni_NativeMethod_nv21CutterToNv12
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint,jbyteArray,jbyteArray,jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
