/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_opengl_OpenglSheard */

#ifndef _Included_com_media_opengl_OpenglSheard
#define _Included_com_media_opengl_OpenglSheard
#ifdef __cplusplus
extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
#include <android/log.h>

#endif
/*
 * Class:     media_jni_MediaNative
 * Method:    creatFfmpeg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_media_opengl_OpenglSheard_creatFfmpeg
        (JNIEnv *, jobject);

/*
 * Class:     media_jni_MediaNative
 * Method:    initContext
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_media_opengl_OpenglSheard_initContext
        (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     media_jni_MediaNative
 * Method:    encode
 * Signature: ([B[B[B[BII)I
 */
JNIEXPORT jint JNICALL Java_com_media_opengl_OpenglSheard_encode
        (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     media_jni_MediaNative
 * Method:    unFfmpeg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_opengl_OpenglSheard_unFfmpeg
        (JNIEnv *, jobject);
/*
 * Class:     media_jni_MediaNative
 * Method:    openStream
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_media_opengl_OpenglSheard_openStream
        (JNIEnv *, jobject, jstring);

/*
 * Class:     media_jni_MediaNative
 * Method:    closeStream
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_media_opengl_OpenglSheard_closeStream
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif

