/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class sc_playvideo_videonative_MediaNative */

#ifndef _Included_sc_playvideo_videonative_MediaNative
#define _Included_sc_playvideo_videonative_MediaNative
#ifdef __cplusplus
extern "C" {
#include "libavcodec/avcodec.h"
#include "libavformat/avformat.h"
#endif
/*
 * Class:     sc_playvideo_videonative_MediaNative
 * Method:    creatFfmpeg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sc_playvideo_videonative_MediaNative_creatFfmpeg
  (JNIEnv *, jobject);

/*
 * Class:     sc_playvideo_videonative_MediaNative
 * Method:    initContext
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_sc_playvideo_videonative_MediaNative_initContext
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     sc_playvideo_videonative_MediaNative
 * Method:    encode
 * Signature: ([B[B[B[BII)I
 */
JNIEXPORT jint JNICALL Java_sc_playvideo_videonative_MediaNative_encode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     sc_playvideo_videonative_MediaNative
 * Method:    unFfmpeg
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_sc_playvideo_videonative_MediaNative_unFfmpeg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
