/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sc_playvideo_videonative_MediaNative */

#ifndef _Included_sc_playvideo_videonative_MediaNative
#define _Included_sc_playvideo_videonative_MediaNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sc_playvideo_videonative_MediaNative
 * Method:    creatFfmpeg
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_sc_playvideo_videonative_MediaNative_creatFfmpeg
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
