/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_media_opengl_OpenglSheard */

#ifndef _Included_com_media_opengl_OpenglSheard
#define _Included_com_media_opengl_OpenglSheard
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
